[tool.black]
line-length = 100

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test"]
python_functions = ["test"]

[tool.coverage.report]
omit = ["*/tests/*", "*/__init__.py", ".venv/*"]
